[package]
name = "sonar"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
cpal = "0.15.2"
crossbeam = "0.8.2"
env_logger = "0.10"
lazy_static = "1.4.0"
log = "0.4"
tiny_http = "0.12.0"
ureq = "2.6.2"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "simd"
harness = false
